export const DAYS_OF_WEEK = {
  MONDAY: 'LUNES',
  TUESDAY: 'MARTES',
  WEDNESDAY: 'MIERCOLES',
  THURSDAY: 'JUEVES',
  FRIDAY: 'VIERNES',
  SATURDAY: 'SABADO',
  SUNDAY: 'DOMINGO',
};

export const USER_TYPES = {
  WALKER: 'WALKER',
  OWNER: 'OWNER',
};

export const PET_GENDER = {
  FEMALE: 'HEMBRA',
  MALE: 'MACHO',
};

export const RESERVATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED_BY_OWNER: 'ACCEPTED_BY_OWNER',
  ACCEPTED_BY_WALKER: 'ACCEPTED_BY_WALKER',
  REJECTED_BY_OWNER: 'REJECTED_BY_OWNER',
  REJECTED_BY_WALKER: 'REJECTED_BY_WALKER',
  REJECTED_BY_SYSTEM: 'REJECTED_BY_SYSTEM',
};
